name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      # <-- This step creates the .streamlit/secrets.toml file in the CI environment
      - name: Create secrets.toml
        run: |
          mkdir -p .streamlit
          echo "${{ secrets.STREAMLIT_SECRETS_TOML }}" > .streamlit/secrets.toml

      - name: Run tests
        run: pytest -v
