# .github/workflows/streamlit-app.yml
name: Streamlit app

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  streamlit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Create secrets.toml
        run: |
          mkdir -p .streamlit
          echo "${{ secrets.STREAMLIT_SECRETS_TOML }}" > .streamlit/secrets.toml

      - name: Debug secrets.toml
        run: cat .streamlit/secrets.toml

      - name: Launch Streamlit
        uses: streamlit/streamlit-app-action@v0.0.3
        with:
          app-path: streamlit_app.py
          ruff: true
          ruff_args: "--fix"
        env:
          SKIP_SMOKE: "false"
